== Patchtest

**Patchtest** is a test framework for community patches based on the standard
https://docs.python.org/2/library/unittest.html[unittest] python module.
As input, it needs tree elements to work propertly: a **patch** in mbox format
(either created with `git format-patch` or fetched from 'patchwork'),
a **test suite** and a **target repository**. In this document we use 'patchtest-oe',
a test suite containing checks targeted for the
https://www.yoctoproject.org/tools-resources/community/mailing-lists[openembedded-core] (
OE-Core, hereafter) mailing list corresponding to the
http://git.openembedded.org/openembedded-core/[OE-Core] target repository.

Patchtest can either run on a <<host,host>> or a <<guest,guest>> machine, depending on which environment
the execution needs to be done. If you plan to test your own patches (a good practice before
these are sent to the mailing list), the easiest way is to install and execute on your local
host; in the other hand, if automatic testing is intended, the guest method
is strongly recommended. Both methods are explained in the following sections.

[[host]]
=== Host
[WARNING]
Testing series coming from 'patchwork' without inspection may be risky on a insufficiently secured
environment; if this is the case, it is [red]#strongly recommended# to execute patchtest in a guest machine
as indicated on the <<guest, guest >> section.

[[env-vars]]
* Define the following environment variables

[source,shell]
----
$ BASE=$PWD/pt
$ PW=$BASE/patchwork
$ PT=$BASE/patchtest
$ PTOE=$BASE/patchtest-oe
$ SUITE=$PTOE/tests
$ OECORE=$BASE/openembedded-core
-----

[[cloning]]
* Clone repositories
[NOTE]
In case your already have the repositories, make sure you update them before testing.
The 'patchtest' and in this case the suite, are live projects and checks are being added
constantly.

[source,shell]
----
$ mkdir $BASE
$ git clone https://github.com/dlespiau/patchwork.git $PW
$ git clone ssh://git@git.yoctoproject.org/patchtest $PT
$ git clone ssh://git@git.yoctoproject.org/patchtest-oe $PTOE
$ git clone git://git.openembedded.org/openembedded-core $OECORE
$ export PATH="$PATH:$PW/git-pw/:$PT"
----

[[path]]
* Append tool paths into the environment 'PATH' variable

[source,shell]
----
$ export PATH="$PATH:$PW/git-pw/:$PT"
----

[[requirements]]
* Install `git-pw` and test suite python requirements using 'pip'
[NOTE]
You can use your distribution package manager instead of 'pip' to install
the requirements

[source,shell]
----
$ cd $PW/git-pw; pip install -r requirements.txt
$ cd $PWOE; pip install -r requirements.txt
----

The tool is ready to be used. It is worth mentioned again that the above
steps consider the 'OE-core' and its corresponding suite 'patchtest-oe'
as examples. Any other project/suite can be configured in a similar way,
just the upstream links would change, but the rest of the instructions
remain valid. Section <<usage, usage>> shows some command line examples
to use the tools just installed.

[[guest]]
=== Guest: a **secure** approach

This method is the recommended way when patch testing is done automatically, i.e. through a 'cronjob'. However,
if you want to test patches your own patches, the <<host,host>> approach is a better option, making it easier and
faster the code cycle ('code-test-code').

* As in the <<host, host>> section, follow the steps <<env-vars, environment variables setting>> and <<cloning, cloning>>.

* TODO: include `chmod` lines to remove write permission into the  '$BASE' folders, so guest can not touch it.

* Poll new series events from the patchwork instance, previously configured as shown <<pw, Patchwork>> section.

[source, shell]
----
$ $PT/scripts/poll $OECORE $BASE
----

The above script will create a new folder under '$BASE' containing the mboxes for every
new series-revision polled. The link 'latest-series' will point to the new folder.

* Using the https://www.yoctoproject.org/[Yocto Project] system, create a 'qemu' machine including
the 'meta-patchtest' layer (located on this repository).
[NOTE]
In case of trouble, please refer to the main Yocto Project https://www.yoctoproject.org/documentation[documentation]
for more information, specially the Yocto Project Quick Start Guide document.

[source,shell]
----
$ cd $BASE
$ git clone git://git.yoctoproject.org/poky
$ cd poky
$ . oe-init-build-env
$ echo "BBLAYERS += \"$PT/meta-patchtest\"' >> conf/bblayers.conf
$ bitbake core-image-patchtest
----

* Launch (from the Poky 'build' folder) the 'qemu' machine with the following parameters

[source, shell]
----
$ runqemu qemux86 \
	core-image-patchtest \
	nographic \
	kvm \
	qemuparams="-fsdev local,id=test_dev,path=$BASE,security_model=mapped \
	            -device virtio-9p-pci,fsdev=test_dev,mount_tag=test_mount"
----

The 'qemu' parameters indicate the shared folder ('$BASE') between host and guest,
containing all necessary data for patchtest to be run in isolation. This folder
is now a (paravirtualized) filesystem using 
https://www.kernel.org/doc/ols/2010/ols2010-pages-109-120.pdf[VirtFS].
With this model, host view shows QEMU as the owner of all files created by any user 
(including root) on the guest hence provides complete isolation and security
[1].

* The machine, once launched, will automatically execute 'patchtest'
with all the new series and results stored in the 'latest-results' folder.

* TODO: we should avoid this step, using a 'qemu' parameter to take
a clean image for every run.
For security reasons, remove the 'qemu' machine

[source,shell]
----
$ cd $POKY/build
$ bitbake -c cleanall core-image-minimal
----

* Finally, in case results need to be posted into the 'patchwork' instance, execute the following script

[source, shell]
----
build$ $PTOE/scripts/post $OECORE $BASE/latest-results
----

where '$BASE/latest-results' contains previous results executed on guest.


[[usage]]
=== Usage

When testing patches locally you can run the tool manually on your local
host. Before testing, follow the <<host, host>> installation
steps. In this section we focus on simple usages of the tool.

'Patchtest' can only accept a **single** patch either from stdin

[source,shell]
----
$ cd $OECORE
$ git format-patch -1 --stdout | patchtest - --start-directory $SUITE
----

or as parameter

[source,shell]
----
$ patchtest somepatch.patch --start-directory $SUITE
----

[[pw]]
=== Patchwork and `git-pw`

New series can be fetched from a 'patchwork' instance using `git-pw` tool
but first some configurations are needed on the target repository.
For the 'OE-core' case, set the following

[source,shell]
----
$ cd $OECORE
$ git config patchwork.default.url http://patchwork.openembedded.org
$ git config patchwork.default.project oe-core
----

and fetch and test in the same command line

[source,shell]
----
$ git pw mbox 1487 | patchtest - --test-dir $SUITE
----

'patchwork' can also store test results, thus two more configurations are needed
in order to post results.

[source,shell]
----
$ git config patchwork.default.user <service account>
$ git config patchwork.default.pass <service password>
----

where the service account is a dedicated patchwork account configured to be a maintainer for a specific patchwork
project, in this case 'OpenEmbedded Core Layer'.