#!/bin/sh

# This is a dummy version that always fails. It is intended to catch
# missing dependencies on the real version.

myname=${0##*/}

echo "The correct version of $myname is not being used!" >&2
echo "Make sure the recipe DEPENDS on 'dbus-glib-native'." >&2

exit 1
