[[guest]]
=== Host installation and Guest execution: a **secure** approach

This method is recommended when patch testing is done automatically (i.e. through a 'cronjob'); however,
if you want to test your own patches, the <<host,host>> approach is a better option for making the code
cycle faster ('code-test-code').

NOTE: The code snipets shown below have been collected into a script 'scripts/pt-cronjob' so they can be easily run
from a cronjob

* As in the <<host, host>> section, follow the <<env-vars, environment variables setting>> and <<cloning, cloning>> steps.

* Fetch latest mboxes from Patchwork, having it previously configured as shown in the <<pw, Patchwork>> section.

[source, shell]
----
fetch-mboxes -r $REPO -m $BASE/mboxes
----

The above script will create a folder '$BASE/mboxes' containing the mboxes for every
new series-revision polled.

[[poky]]
* Create a qemu machine using the https://www.yoctoproject.org/[Yocto Project] build system
[NOTE]
For troubleshooting, please refer to the main Yocto Project https://www.yoctoproject.org/documentation[documentation], specially the http://www.yoctoproject.org/docs/latest/yocto-project-qs/yocto-project-qs.html[Yocto Project Quick Start Guide].

[source,shell]
----
GUEST="$HOME/patchtest-guest"
mkdir -p $GUEST
----

[source,shell]
----
cd $GUEST
git clone git://git.yoctoproject.org/patchtest
git clone git://git.openembedded.org/meta-openembedded
git clone git://git.yoctoproject.org/poky
----

[source,shell]
----
cd $GUEST/poky
source oe-init-build-env
echo "MACHINE = \"qemux86-64\"" >> conf/local.conf
echo "SERIAL_CONSOLES_CHECK ?= \"\${SERIAL_CONSOLES}\"" >> conf/local.conf
echo "BBLAYERS += \"$GUEST/meta-openembedded/meta-oe\"" >> conf/bblayers.conf
echo "BBLAYERS += \"$GUEST/meta-openembedded/meta-python\"" >> conf/bblayers.conf
echo "BBLAYERS += \"$GUEST/patchtest/meta-patchtest\"" >> conf/bblayers.conf
bitbake core-image-patchtest
----

* Launch (from the Poky 'build' folder and with the environment prepared) the 'qemu' machine with the following parameters

[source, shell]
----
runqemu qemux86-64
	core-image-patchtest \
	nographic \
	kvm \
	qemuparams="-snapshot \
		    -fsdev local,id=test_dev,path=$BASE,security_model=mapped \
	            -device virtio-9p-pci,fsdev=test_dev,mount_tag=test_mount"
----

The 'qemu' parameters indicate the shared folder ('$BASE') between host and guest,
containing all necessary data for patchtest to be run in isolation. This folder
is now a (paravirtualized) filesystem using 
https://www.kernel.org/doc/ols/2010/ols2010-pages-109-120.pdf[VirtFS].
With this model, host view shows QEMU as the owner of all files created by any user 
(including root) on the guest hence provides complete isolation and security
[1].

* Once launched, the virtual machine will automatically execute 'patchtest'

* Currently, the machine is not being turned off automatically, so one needs to
login (as root) and halt the machine manually.

* Once on host again, the results are stored into the folder '$BASE/results'. Now you
can `cd` into the folder and explore the results with `git-log` or `git-show`:

[source,shell]
-----
git log --show-notes=*
----

