[[guest]]
=== Host installation and Guest execution: a **secure** approach

This method is the recommended way when patch testing is done automatically, i.e. through a 'cronjob'. However,
if you want to test your own patches, the <<host,host>> approach is a better option, making it easier and
faster the code cycle ('code-test-code').

NOTE: The below code snipets have been collected into a script 'scripts/pt-cronjob' so it can be easily run
from a cronjob.

* As in the <<host, host>> section, follow the steps <<env-vars, environment variables setting>> and <<cloning, cloning>>.

* Fetch latest mboxes from patchwork, previously configured as shown <<pw, Patchwork>> section.

[source, shell]
----
fetch-mboxes -r $REPO -m $BASE/mboxes
----

The above script will create a folder '$BASE/mboxes' containing the mboxes for every
new series-revision polled.

[[poky]]
* Using the https://www.yoctoproject.org/[Yocto Project] system, create a 'qemu' machine
[NOTE]
In case of trouble, please refer to the main Yocto Project https://www.yoctoproject.org/documentation[documentation]
for more information, specially the Yocto Project Quick Start Guide document.

[source,shell]
----
cd $BASE
git clone git://git.openembedded.org/meta-openembedded
git clone git://git.yoctoproject.org/poky
cd poky
. oe-init-build-env
echo "BBLAYERS += \"$BASE/meta-openembedded/meta-oe\"" >> conf/bblayers.conf
echo "BBLAYERS += \"$BASE/meta-openembedded/meta-python\"" >> conf/bblayers.conf
echo "BBLAYERS += \"$PT/meta-patchtest\"" >> conf/bblayers.conf
bitbake core-image-patchtest
----

* Launch (from the Poky 'build' folder) the 'qemu' machine with the following parameters

[source, shell]
----
runqemu qemux86 \
	core-image-patchtest \
	nographic \
	kvm \
	qemuparams="-snapshot \
		    -fsdev local,id=test_dev,path=$BASE,security_model=mapped \
	            -device virtio-9p-pci,fsdev=test_dev,mount_tag=test_mount"
----

The 'qemu' parameters indicate the shared folder ('$BASE') between host and guest,
containing all necessary data for patchtest to be run in isolation. This folder
is now a (paravirtualized) filesystem using 
https://www.kernel.org/doc/ols/2010/ols2010-pages-109-120.pdf[VirtFS].
With this model, host view shows QEMU as the owner of all files created by any user 
(including root) on the guest hence provides complete isolation and security
[1].

* The machine, once launched, will automatically execute 'patchtest'

* Currently, the machine is not turn off automatically, so one needs to
login and halt the machine manually.

* Once on host again, results are stored into the folder '$BASE/results'. `cd` into the folder
and explored the results with `git-log` or `git-show`:

[source,shell]
-----
git log --show-notes=*
----

