[[intro]]
=== Introduction

**Patchtest** is a test framework for community patches based on the standard
https://docs.python.org/2/library/unittest.html[unittest] python module.
As input, it needs tree elements to work propertly: a **patch** in mbox format
(either created with `git format-patch` or fetched from 'patchwork'),
a **test suite** and a **target repository**. In this document we use 'patchtest-oe',
a test suite containing checks targeted for the
https://www.yoctoproject.org/tools-resources/community/mailing-lists[openembedded-core] (
OE-Core, hereafter) mailing list corresponding to the
http://git.openembedded.org/openembedded-core/[OE-Core] target repository.

Patchtest can either run on a <<host,host>> or a <<guest,guest>> machine, depending on which environment
the execution needs to be done. If you plan to test your own patches (a good practice before
these are sent to the mailing list), the easiest way is to install and execute on your local
host; in the other hand, if automatic testing is intended, the guest method
is strongly recommended. Both methods are explained in the following sections.

