[[scripts]]
=== Scripts

Under the 'scripts' folder, there are several scripts that can be useful
with the following purposes:

* 'fetch-mboxes': Fetch mboxes from a patchwork instance and place these into a directory
* 'test-mboxes' : Test one or more mboxes, possible assembling these into into a git-branch and/or
collecting results into a repository

The following subsections describe some possible scenarios. Before proceding, examples assume the
following environment variables already defined:

* `REPO`   : Path to a patchwork configured repository
* `PROJECT`: Patchwork project name
* `SUITE`  : Starting directory of the test suite

==== Testing local patches

Testing patches before these are sent to the mailing list is a good practice. Let's say
that you are working on a branch and you want to test all commits that have diverted from master

[source,shell]
----
$ BN=$(git rev-parse --abbrev-ref HEAD)       # This gets the current branch name
$ git format-patch master..$BN -o $BN-mboxes  # Get all commits and store these
----

Now, you can test your mboxes (commits) with

[source,shell]
----
$ test-mboxes -r $REPO -s $SUITE -o $BN-patchtest $BN-mboxes
----

The directory '$BN-patchtest' is in repository where you can review the patchtest results
with

[source,shell]
-----
$ cd $BN-patchtest
$ git log --show-notes=patchtest-results-*
----

If you do not care about storing a results, you can always use the base script with a
certain patch

[source,shell]
----
$ patchtest $BN-mboxes/0001-* -s $SUITE
----

==== Monitoring a patchwork instance

The following command lines can be collected into a single a script, and call it from a cronjob

[source,shell]
----
$ TSFILE="$REPO/.git-pw.$PROJECT.poll.timestamp"
$ TS="$(test -f $TSFILE && cat $TSFILE || date --iso-8601 | tee $TSFILE)"
$ MBOXDIR="$TS/mbox"
$ RESULTSDIR="$TS/results"
$ fetch-mboxes -r $REPO -m $MBOXDIR
----

If test execution is done at host (insecure as explained in the <<guest,guest>> section), run

[source,shell]
----
$ test-mboxes  -r $REPO -s $SUITE -o $RESULTSDIR -a $TS-patchtest $MBOXDIR
----

where `$RESULTSDIR` would contain the results from those mboxes (stored on `$MBOXDIR`)
fetched from a particular timestamp, defined by `$TS`. As explained before, commits on
`$RESULTSDIR` have git-notes, so you can review them with

[source,shell]
----
$ git log --show-notes=patchtest-results-*
----
