#!/bin/bash -eu
# ex:ts=4:sw=4:sts=4:et
# -*- tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-
#
# fetch-mboxes: Fetch mboxes from a patchwork instance
#
# Copyright (C) 2016 Intel Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# defaults values
repodir=''
mboxdir='.'
since=''

function usage() {
    cat << EOF
\$ $(basename $0) OPTIONS [SERIES]

where OPTIONS are

    -r <repodir>   : Repository
    -m <mboxdir>   : Directory where mboxes are stored. Defaults to $mboxdir
    -s <timestamp> : Poll events since the defined timestamp

and optional SERIES separated with spaces, i.e. '100 87'. Revision can be included and these appears after the series,
joined with a dot, i.e. '100.2 87'. If series are not given, it will poll patchwork events using <timestamp> if given,
otherwise it uses the timestamp defined on the corresponding .git-pw file, the latter produced by git-pw command. In case
any of these are not present, the script wont do anything except that the .git-pw files is now present and populated with
timestamp of last polled series event.

EOF
>&2

    exit 1
}

while getopts ":r:m:s:h" opt; do
    case $opt in
	r)
	    repodir=$OPTARG
	    ;;
	m)
	    mboxdir=$OPTARG
	    ;;
	s)
	    since=$OPTARG
	    ;;
	h)
	    usage
	    ;;
	\?)
	    echo "Invalid option: -$OPTARG" >&2
	    usage
	    ;;
	:)
	    echo "Option -$OPTARG requires an argument." >&2
	    usage
	    ;;
    esac
done
shift $((OPTIND-1))

[ -z "$repodir" ]   && { echo "Indicate the repository"; usage; }
[ ! -d $repodir ]   && { echo "Repository does not exit"; usage; }

repodir=$(realpath -e $repodir)
series="$@"

# events come in pairs separated by a dot
if [ -z "$series" ]; then
    series="$(poll-events $repodir $since)"
fi

if [ -n "$series" ]; then

    # create the mbox directory in case it does not exit
    test ! -d "$mboxdir" && { mkdir -p $mboxdir; }

    # get the real path
    mboxdir=$(realpath -e $mboxdir)

    # fetch series
    for s in $series; do
	sid="$(echo $s | cut -d. -f1)"
	cmd="git pw mbox $sid --link --link-name $s"
	# in case there is revision, consider it
	if echo $s | grep '\.' --quiet; then
	    rid="$(echo $s | cut -d. -f2)"
	    cmd="$cmd --revision $rid"
	    mboxfile="$mboxdir/$sid.$rid.mbox"
	    echo -e "Series/Revision $sid/$rid"
	else
	    mboxfile="$mboxdir/$sid.mbox"
	    echo -e "Series/Revision $sid/latest"
	fi
	( cd $repodir
	  $cmd > $mboxfile
	)
	echo -e "\tStore into $mboxdir"
	echo -e ""
    done
else
    echo -e "No new series events"
fi
