#!/bin/sh

# scripts/oe-selftest: calls oe-selftest-internal in a isolated environment
#
# Copyright (c) 2013-2017 Intel Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

# Before anything else, check oe-core environment
if [ -z "$BUILDDIR" ]; then
    echo "Please initialize the OE-Core environment through oe-init-build-env script"
    exit 1
fi

# Variable definitions
ORIGBUILDDIR="$BUILDDIR"
OESELFTESTSCRIPTDIR="$(which oe-selftest)"
SCRIPTSDIR="$(dirname $OESELFTESTSCRIPTDIR)"
OECOREDIR="$(dirname $SCRIPTSDIR)"

# oe-selftest-$$ related
OESELFTESTDIR="$ORIGBUILDDIR/oe-selftest-$$"
OESELFTESTBUILDDIR="$OESELFTESTDIR/build"

# Return immediately in case no test execution
ADDTESTS="$(echo "$@" | grep -i '\-a')"
SOMETESTS="$(echo "$@" | grep -i '\-r')"
if [ -z "$ADDTESTS" -a -z "$SOMETESTS" ]; then
    if [ -z "$@" ]; then
	oe-selftest-internal -h
    else
	oe-selftest-internal "$@"
    fi
    exit 0
fi

# Create directories (build, build/conf and layers)
mkdir -p $OESELFTESTDIR $OESELFTESTBUILDDIR/conf $OESELFTESTLAYERSDIR

# Populate the new build/conf, bblayers.conf will be touch latter to reflect new layer structure
cp $ORIGBUILDDIR/conf/* $OESELFTESTBUILDDIR/conf

# Copy OE-Core meta directories
cp -a $OECOREDIR/meta-selftest  $OESELFTESTDIR
cp -a $OECOREDIR/meta-skeleton  $OESELFTESTDIR
cp -a $OECOREDIR/meta-yocto-bsp $OESELFTESTDIR

# Copy non-metadata files
cp -a $OECOREDIR/bitbake        $OESELFTESTDIR
cp -a $SCRIPTSDIR               $OESELFTESTDIR
cp $OECOREDIR/oe-init-build-env $OESELFTESTDIR
cp $OECOREDIR/.templateconf     $OESELFTESTDIR

# Copy all layers define in BBLAYERS and construct the new bblayers.conf at the same time
BBLAYERS="$(bitbake -e | grep ^BBLAYERS= | sed -e s/BBLAYERS=// -e s/\"//g)"
for src in $BBLAYERS; do
    cp -a $src $OESELFTESTDIR
    # rename the new layer into the new bblayers.conf
    tgt="$OESELFTESTDIR/$(basename $src)"
    sed -e "s|$src|$tgt|" -i $OESELFTESTBUILDDIR/conf/bblayers.conf
done

# Reinitialized environment with new metadata and templateconf environement
cd $OESELFTESTDIR
source ./oe-init-build-env $OESELFTESTBUILDDIR

# Execute the tests throught oe-selftest-internal
oe-selftest-internal "$@"

OESELFTESTRC="$?"

# Echo working folder
echo -e "\nAll work done under $OESELFTESTDIR\n"

exit $OESELFTESTRC
