#!/bin/bash -eur
# ex:ts=4:sw=4:sts=4:et
# -*- tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-
#
# test-commits: run patchtest from a origin commit (since) and report
#               raw results
#
# Copyright (C) 2016 Intel Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

origin=$1
test_suite=$2

usage() {
    echo -e "Runs patchtest starting at certain commit using the specified test suite"
    echo -e "\$ $0 <since commit> <path to test suite>"
    echo
    echo -e "For example, test last 10 commits"
    echo
    echo -e "\$ $0 HEAD~10 $HOME/patchtest-oe/tests"
    echo
}

[ -z $origin ]     && { usage; exit -1; }
[ -z $test_suite ] && { usage; exit -1; }

for commit in $(git rev-list $origin..HEAD --reverse); do
    git format-patch "$commit^1..$commit" --stdout | \
    patchtest - --commit "$commit^1" --test-dir $test_suite -f -m
done

