# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-04 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0018_project_specific'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distro',
            name='up_id',
        ),
        migrations.AlterField(
            model_name='build',
            name='recipes_parsed',
            field=models.IntegerField(default=1),
        ),
    ]
