#!/bin/sh
# pkgconf wrapper to deal with pkg-config/pkgconf compatibility issues
#
# Copyright (C) 2015 Christopher Larson <chris_larson@mentor.com>
# License: MIT (see COPYING.MIT at the root of the repository for terms)

# https://github.com/pkgconf/pkgconf/commit/fd1b8ccca68abe52e1158aa3e5ef42267d952b74

export PKG_CONFIG_FDO_SYSROOT_RULES="1"

exec pkgconf "$@"
